name: Deploy RDP Server

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup RDP
        run: |
          sudo apt update
          sudo apt install -y xrdp xfce4 xfce4-goodies
          sudo systemctl start xrdp
          echo "RDP Server is Ready!"
