name: Free RDP  

on:  
  push:  
    branches: [ main ]  
  workflow_dispatch:  

jobs:  
  build:  
    runs-on: ubuntu-latest  

    steps:  
      - name: Set up RDP  
        run: |  
          sudo apt update  
          sudo apt install -y xrdp  
          sudo systemctl enable xrdp  
          sudo systemctl start xrdp  
